/*
 FusionCharts JavaScript Library - Tree Map Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.12.0-rc.2
*/
(function(O){"object"===typeof module&&"undefined"!==typeof module.exports?module.exports=O:O(FusionCharts)})(function(O){O.register("module",["private","modules.renderer.js-treemap",function(){function ba(a){return a?a.replace(/^#*/,"#"):"#E5E5E5"}function x(a,c,d){this.label=a;this.value=parseFloat(c,10);this.colorValue=parseFloat(d,10);this.prev=this.next=void 0;this.meta={}}function P(){this._b=[];this._css=void 0;this.rangeOurEffectApplyFn=function(){};this.statePointerLow={value:void 0,index:void 0};
this.statePointerHigh={value:void 0,index:void 0}}var ja,ka,ha,la,J=this.hcLib,ca=J.chartAPI,V=Math,Y=V.max,ma=V.round,sa=V.tan,na=V.min,ta=V.PI,oa=J.extend2,Z=this.window,ua=J.parsexAxisStyles,V=J.Raphael,pa=J.graphics,da=pa.convertColor,qa=pa.getLightColor,z=this.raiseEvent,y=J.pluckNumber,K=J.pluck,va=J.each,ea=J.BLANKSTRING,wa="rgba(192,192,192,"+(/msie/i.test(Z.navigator.userAgent)&&!Z.opera?.002:1E-6)+")",Z=!J.CREDIT_REGEX.test(Z.location.hostname),ra=J.plotEventHandler,fa=J.schedular,xa=J.preDefStr.DEFAULT;
V.addSymbol({backIcon:function(a,c,d){--d;var b=c+d,g=b-d/2,p=a+d,r=g-d;return["M",a,c-d,"L",a-d,c,a,b,a,g,p,g,p,r,p-d,r,"Z"]},homeIcon:function(a,c,d){--d;var b=2*d,g=a-d,p=g+b/6,r=c+d,A=p+b/4,m=r-d/2,k=A+b/6,t=m+d/2,n=k+b/4,f=t-d;return["M",a,c-d,"L",g,c,p,c,p,r,A,r,A,m,k,m,k,t,n,t,n,f,n+b/6,f,"Z"]}});x.prototype.constructor=x;x.prototype.getCSSconf=function(){return this.cssConf};x.prototype.getPath=function(){return this.path};x.prototype.setPath=function(){var a=this.getParent();this.path=(a?
a.getPath():[]).concat(this)};x.prototype.addChild=function(a){a instanceof x&&(this.next=this.next||[],[].push.call(this.next,a),a.setParent(this));return this.next};x.prototype.getChildren=function(){return this.next};x.prototype.addChildren=function(a,c){var d=this.getChildren()||(this.next=[]),b=d.length;c||(c=b-1);d.splice(c>b-1?b-1:0>c?0:c,0,a);a.setParent(this)};x.prototype.getDepth=function(){return this.meta.depth};x.prototype.isLeaf=function(a){return(a?this.getDepth()<a:!0)&&this.next};
x.prototype.setParent=function(a){a instanceof x&&(this.prev=a);return this};x.prototype.getSiblingCount=function(a){var c,d=0,b=this;if(this instanceof x){c=this.getParent();if(a){for(;b;)(b=b.getSibling(a))&&(d+=1);return d}if(c)return c.getChildren().length}};x.prototype.getParent=function(){return this.prev};x.prototype.getLabel=function(){return this.label};x.prototype.getValue=function(){return this.value};x.prototype.setValue=function(a,c){this.value=c?this.value+a:a};x.prototype.getColorValue=
function(){return this.colorValue};x.prototype.getSibling=function(a){a=a.toLowerCase();var c=this.getParent(),d=this.getLabel(),b,g;if(c)for(c=c.getChildren(),b=0;b<c.length;b++)if(g=c[b],g=g.getLabel(),g===d)switch(a){case "left":return c[b-1];case "right":return c[b+1]}};x.prototype.setMeta=function(a,c){this.meta[a]=c};x.prototype.setDepth=function(a){this.meta.depth=a};x.prototype.getMeta=function(a){return a?this.meta[a]:this.meta};P.prototype.constructor=P;P.prototype.resetPointers=function(){this.statePointerLow=
{value:void 0,index:void 0};this.statePointerHigh={value:void 0,index:void 0}};P.prototype.setRangeOutEffect=function(a,c){this._css=a;this.rangeOurEffectApplyFn=c};P.prototype.addInBucket=function(a){var c=this._b,d=a.getColorValue(),b=0,g=c.length-1;if(d){a:{for(var p,r;b<=g;)if(p=(b+g)/2|0,r=c[p],r=r.getColorValue(),r<d)b=p+1;else if(r>d)g=p-1;else{d=p;break a}d=~g}c.splice(Math.abs(d),0,a)}};P.prototype.moveLowerShadePointer=function(a){var c=this._b,d,b,g,p=this.statePointerLow;d=p.index;b=p.value;
var r=!1;d=void 0!==d?d:0;b=void 0!==b?b:Number.NEGATIVE_INFINITY;if(a!==b){if(b<=a){for(;;){g=(b=c[d++])?b.getColorValue():0;if(a<g||!b)break;r=!0;b.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(b,this._css)}d=r?d-2:d-1}else{for(;;){g=(b=c[d--])?b.getColorValue():0;if(a>=g||!b)break;b.cssConf=b.cssConf||{};r=!0;delete b.rangeOutEffect;b.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(b,b.cssConf)}d=r?d+2:d+1}p.index=d;p.value=a}};P.prototype.moveHigherShadePointer=function(a){var c=
this._b,d=c.length,b,g,p=this.statePointerHigh;g=p.index;b=p.value;var r=!1,d=void 0!==g?g:d-1;b=void 0!==b?b:Number.POSITIVE_INFINITY;if(a!==b){if(b>a){for(;;){g=(b=c[d--])?b.getColorValue():0;if(a>=g||!b)break;r=!0;b.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(b,this._css)}d=r?d+2:d+1}else{for(;;){g=(b=c[d++])?b.getColorValue():0;if(a<g||!b)break;b.cssConf=b.cssConf||{};r=!0;delete b.rangeOutEffect;b.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(b,b.cssConf)}d=r?d-2:d-1}p.index=
d;p.value=a}};ca("treemap",{friendlyName:"TreeMap",standaloneInit:!0,hasGradientLegend:!0,creditLabel:Z,defaultDatasetType:"treemap",enableMouseOutEvent:!0,applicableDSList:{treemap:!0},_mouseEvtHandler:function(a){var c=a.data,d=c.chart,c=c.mouseTracker,b=d.config,g=b.canvasLeft,p=b.canvasRight,r=b.canvasBottom,A=b.canvasTop,m=b.datasetOrder||d.components.dataset,b=J.getMouseCoordinate(d.linkedItems.container,a.originalEvent,d),k=b.chartX,t=b.chartY,n,f,Q=!1,l=m.length,q,w=c._lastDatasetIndex,b=
c._lastPointIndex;if(k>g&&k<p&&t>A&&t<r||d.config.plotOverFlow)for(;l--&&!Q;)(n=m[l])&&(f=n._getHoveredPlot&&n._getHoveredPlot(k,t))&&f.hovered&&(Q=!0,f.datasetIndex=l,q=c._getMouseEvents(a,f.datasetIndex,f.pointIndex));(!Q||q&&q.fireOut)&&void 0!==w&&(delete c._lastDatasetIndex,delete c._lastPointIndex,m[w]&&m[w]._firePlotEvent&&m[w]._firePlotEvent("mouseout",b,a));if(Q)for(d=q.events&&q.events.length,c._lastDatasetIndex=f.datasetIndex,b=c._lastPointIndex=f.pointIndex,f=0;f<d;f+=1)n&&n._firePlotEvent&&
n._firePlotEvent(q.events[f],b,a)},addData:function(){var a=this._ref.algorithmFactory,c=Array.prototype.slice.call(arguments,0);c.unshift("addData");c.unshift(this._getCleanValue());a.realTimeUpdate.apply(this,c)},removeData:function(){var a=this._ref.algorithmFactory,c=Array.prototype.slice.call(arguments,0);c.unshift("deleteData");c.unshift(this._getCleanValue());a.realTimeUpdate.apply(this,c)},_createToolBox:function(){var a,c,d,b,g=this.components;a=g.chartMenuBar;c=g.actionBar;a&&a.drawn||c&&
c.drawn||(ca.mscartesian._createToolBox.call(this),a=g.tb,c=a.getAPIInstances(a.ALIGNMENT_HORIZONTAL),d=c.Symbol,c=(g.chartMenuBar||g.actionBar).componentGroups[0],b=new d("backIcon",!1,(a.idCount=a.idCount||0,a.idCount++),a.pId),a=new d("homeIcon",!1,a.idCount++,a.pId),c.addSymbol(a,!0),c.addSymbol(b,!0),g.toolbarBtns={back:b,home:a})},_getCleanValue:function(){var a=this.components.numberFormatter;return function(c){return a.getCleanValue(c)}},_createDatasets:function(){var a=this.components,c=
this.jsonData,d=c.dataset,d=c.data||d&&d[0].data,b=this.defaultDatasetType,g=[];d&&d.length||this.setChartMessage();va(d,function(a){a.vline||g.push(a)});c={data:g};this.config.categories=g;a=a.dataset||(a.dataset=[]);d?b&&(d=O.get("component",["dataset",b]))&&(a[0]?(a[0].JSONData=g[0],a[0].configure()):(this._dsInstance=d=new d,a.push(d),d.chart=this,d.init(c))):this.setChartMessage()},init:function(){var a={},c={},d={};this._ref={afAPI:ja(a,c,d),algorithmFactory:ka(a,c,d),containerManager:la(a,
c,d),treeOpt:ha};ca.guageBase.init.apply(this,arguments)}},ca.guageBase,{enablemousetracking:!0});O.register("component",["dataset","TreeMap",{type:"treemap",pIndex:2,customConfigFn:"_createDatasets",init:function(a){this.JSONData=a.data[0];this.components={};this.conf={};this.graphics={elemStore:{rect:[],label:[],highlight:[],hot:[],polypath:[]}};this.configure()},configure:function(){var a,c=this.chart,d=c.components,b=this.conf,c=c.jsonData.chart;b.metaTreeInf={};b.algorithm=(c.algorithm||"squarified").toLowerCase();
b.horizontalPadding=y(c.horizontalpadding,5);b.horizontalPadding=0>b.horizontalPadding?0:b.horizontalPadding;b.verticalPadding=y(c.verticalpadding,5);b.verticalPadding=0>b.verticalPadding?0:b.verticalPadding;b.showParent=y(c.showparent,1);b.showChildLabels=y(c.showchildlabels,0);b.highlightParentsOnHover=y(c.highlightparentsonhover,0);b.defaultParentBGColor=K(c.defaultparentbgcolor,void 0);b.defaultNavigationBarBGColor=K(c.defaultnavigationbarbgcolor,b.defaultParentBGColor);b.showTooltip=y(c.showtooltip,
1);b.baseFontSize=y(c.basefontsize,10);b.baseFontSize=1>b.baseFontSize?1:b.baseFontSize;b.labelFontSize=y(c.labelfontsize,void 0);b.labelFontSize=1>b.labelFontSize?1:b.labelFontSize;b.baseFont=K(c.basefont,"Verdana, Sans");b.labelFont=K(c.labelfont,void 0);b.baseFontColor=K(c.basefontcolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1");b.labelFontColor=K(c.labelfontcolor,void 0);b.labelFontColor&&(b.labelFontColor=b.labelFontColor.replace(/^#?([a-f0-9]+)/ig,"#$1"));b.labelFontBold=y(c.labelfontbold,
0);b.labelFontItalic=y(c.labelfontitalic,0);b.plotBorderThickness=y(c.plotborderthickness,1);b.plotBorderThickness=0>b.plotBorderThickness?0:5<b.plotBorderThickness?5:b.plotBorderThickness;b.plotBorderColor=K(c.plotbordercolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1");b.tooltipSeparationCharacter=K(c.tooltipsepchar,",");b.plotToolText=K(c.plottooltext,"");b.parentLabelLineHeight=y(c.parentlabellineheight,12);b.parentLabelLineHeight=0>b.parentLabelLineHeight?0:b.parentLabelLineHeight;b.labelGlow=
y(c.labelglow,1);b.labelGlowIntensity=y(c.labelglowintensity,100)/100;b.labelGlowIntensity=0>b.labelGlowIntensity?0:1<b.labelGlowIntensity?1:b.labelGlowIntensity;b.labelGlowColor=K(c.labelglowcolor,"#ffffff").replace(/^#?([a-f0-9]+)/ig,"#$1");b.labelGlowRadius=y(c.labelglowradius,2);b.labelGlowRadius=0>b.labelGlowRadius?0:10<b.labelGlowRadius?10:b.labelGlowRadius;b.btnResetChartTooltext=K(c.btnresetcharttooltext,"Back to Top");b.btnBackChartTooltext=K(c.btnbackcharttooltext,"Back to Parent");b.rangeOutBgColor=
K(c.rangeoutbgcolor,"#808080").replace(/^#?([a-f0-9]+)/ig,"#$1");b.rangeOutBgAlpha=y(c.rangeoutbgalpha,100);b.rangeOutBgAlpha=1>b.rangeOutBgAlpha||100<b.rangeOutBgAlpha?100:b.rangeOutBgAlpha;a=y(c.maxdepth);b.maxDepth=void 0!==a?Y(a,1):void 0;a=b.showNavigationBar=y(c.shownavigationbar,1);b.slicingMode=K(c.slicingmode,"alternate");b.navigationBarHeight=y(c.navigationbarheight);b.navigationBarHeightRatio=y(c.navigationbarheightratio);b.navigationBarBorderColor=K(c.navigationbarbordercolor,b.plotBorderColor).replace(/^#?([a-f0-9]+)/ig,
"#$1");b.navigationBarBorderThickness=a?y(c.navigationbarborderthickness,b.plotBorderThickness):0;b.seperatorAngle=y(c.seperatorangle)*(ta/180);d.postLegendInitFn({min:0,max:100});b.isConfigured=!0},_getHoveredPlot:function(a,c){var d,b;for(b=(this.kdTree||[]).length;b--&&!(d=this.kdTree[b].searchTreemap(a,c)););if(d)return this.pointObj=d,{pointIndex:d.i||d.index,hovered:!0,pointObj:d}},kdTreeAbs:function(a){function c(a,c,b){return a>=c&&a<=b}function d(a,c,u,v){var e={},h;h=v?"y":"x";if(c===u)return e.point=
a[c],e;if(1===u-c)return a[c][h]>a[u][h]?(e.point=a[c],e.left={point:a[u]}):(e.point=a[u],e.left={point:a[c]}),e;h=c+u>>1;v?g(a,h,c,u):b(a,h,c,u);e.point=a[h];e.left=d(a,c,h-1,!v);e.right=d(a,h+1,u,!v);return e}function b(a,c,u,d){for(var e,h,B,C,l;d>u;){600<d-u&&(e=d-u+1,h=c-u+1,B=f(e),C=.5*Q(2*B/3),l=.5*t(B*C*(e-C)/e)*(0>h-e/2?-1:1),B=m(u,k(c-h*C/e+l)),e=n(d,k(c+(e-h)*C/e+l)),b(a,c,B,e));e=a[c];h=u;C=d;p(a,u,c);for(a[d].x>e.x&&p(a,u,d);h<C;){p(a,h,C);h++;for(C--;a[h].x<e.x;)h++;for(;a[C].x>e.x;)C--}a[u].x===
e.x?p(a,u,C):(C++,p(a,C,d));C<=c&&(u=C+1);c<=C&&(d=C-1)}}function g(a,c,b,d){for(var e,h,B,l,G;d>b;){600<d-b&&(e=d-b+1,h=c-b+1,B=f(e),l=.5*Q(2*B/3),G=.5*t(B*l*(e-l)/e)*(0>h-e/2?-1:1),B=m(b,k(c-h*l/e+G)),e=n(d,k(c+(e-h)*l/e+G)),g(a,c,B,e));e=a[c];h=b;l=d;p(a,b,c);for(a[d].y>e.y&&p(a,b,d);h<l;){p(a,h,l);h++;for(l--;a[h].y<e.y;)h++;for(;a[l].y>e.y;)l--}a[b].y===e.y?p(a,b,l):(l++,p(a,l,d));l<=c&&(b=l+1);c<=l&&(d=l-1)}}function p(a,c,b){var d=a[c];a[c]=a[b];a[b]=d}var r=a&&a[0]&&a[0].plotDetails.rect||
5,A,m=Math.max,k=Math.floor,t=Math.sqrt,n=Math.min,f=Math.log,Q=Math.exp,l=Math.pow;A={};a=a||[];for(A=a.length;A--;)a[A].r>r&&(r=a[A].r),a[A].x=+a[A].plotDetails.rect.x,a[A].y=+a[A].plotDetails.rect.y;A={tree:d(a,0,a.length-1,!1),search:function(a,b){function d(e){var u=c(a,e.x1,e.x2)&&c(b,e.y1,e.y2),f;f=e.point.y;f=t(l(a-e.point.x,2)+l(b-f,2));h?u?g?e.point.i>h.point.i&&(h=e,g=u,n=f):(h=e,g=u,n=f):!g&&f<n&&(h=e,g=u,n=f):(h=e,g=u,n=f)}function f(a){a&&a.point&&(c(a.point.x,B,C)&&c(a.point.y,k,m)&&
d(a),B<=a.point.x&&e(a.left),C>=a.point.x&&e(a.right))}function e(a){a&&a.point&&(c(a.point.x,B,C)&&c(a.point.y,k,m)&&d(a),k<=a.point.y&&f(a.left),m>=a.point.y&&f(a.right))}var h,B=a-r,C=a+r,k=b-r,m=b+r,g=!1,n=0;f(this.tree);return h&&h.point||h},searchTreemap:function(a,c){var b,d=function(e,h){if(e&&e.point){var l=e.point.x,f=l+e.point.plotDetails.rect.width,t=e.point.y,k=t+e.point.plotDetails.rect.height;e.point.x2=f;e.point.y2=k;a>=l&&a<=f&&c>=t&&c<=k&&(l=e.point,b?l.i>b.i&&(b=l):b=l);d(e.left,
!h);d(e.right,!h)}};d(this.tree,!1);return b}};a.sort(function(a,c){return a.i-c.i});return A},kdTreePartioning:function(){var a=this.chart.config.trackerConfig,c,d=[];for(c=a.length;c--;)a[c].i=c,void 0===d[a[c].node.meta.depth]&&(d[a[c].node.meta.depth]=[]),d[a[c].node.meta.depth].push(a[c]);this.kdTree=[];for(c=d.length;c--;)this.kdTree[c]=this.kdTreeAbs&&this.kdTreeAbs(d[c])},_rolloverResponseSetter:function(a,c,d){var b=c.getData()||{};c&&(c.attr(b.setRolloverAttr),ra.call(c,a,d,"DataPlotRollOver"))},
_rolloutResponseSetter:function(a,c,d){var b=c.getData()||{};c&&(c.attr(b.setRolloutAttr),ra.call(c,a,d,"DataPlotRollOut"))},_firePlotEvent:function(a,c,d){var b=this.conf,g=this.chart,p=g.getJobList(),r=g.components.paper;c=this.chart.config.trackerConfig[c||0];var A=g.graphics.trackerGroup,m=c&&c.node&&c.node.plotItem,k=c&&c.evtFns&&c.evtFns.tooltip[0],t=g.components.paper.canvas.style,n=J.toolTip;d=d.originalEvent;var f=this.graphics.singleTracker,Q=this.pointObj.plotDetails,l=Q&&Q.rect,b=b.highlightParentsOnHover,
q=c&&c.node.path,w=(q=q&&q[q.length-2])&&q.rect;f||(f=this.graphics.singleTracker=r.rect(A));m?b&&q?f.attr({x:w.x,y:w.y,width:w.width,height:w.height,stroke:"rgba(255,255,255,0)"}):(Q?f.attr({x:l.x||0,y:l.y||0,width:l.width||0,height:l.height||0,stroke:"rgba(255,255,255,0)"}):f.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"}),f.toFront()):m=c&&c.node.dirtyNode.plotItem;if(m)switch(a){case "mouseover":k&&(n.setStyle(r),n.setPosition(d),n.draw(k,r));t.cursor="pointer";c.evtFns.hover[0](f);
break;case "mouseout":f.attr({x:0,y:0,width:0,height:0,stroke:"#ffffff","stroke-width":"0px"});n.hide();t.cursor=xa;f.toFront();this._rolloutResponseSetter(g,m,d);break;case "click":k&&(n.setStyle(r),n.setPosition(d),n.draw(k,r));c&&c.evtFns&&c.evtFns.click&&c.evtFns.click[0]();p.trackerDrawID.push(fa.addJob(this.kdTreePartioning,this,[],J.priorityList.tracker));break;case "mousemove":k&&(n.setPosition(d),n.draw(k,r))}},draw:function(){var a=this.conf,c=this.chart,d=c.config.trackerConfig,b=c.getJobList(),
g=c.config,p=c.components,r=g.canvasLeft,A=g.canvasRight,m=g.canvasBottom,k=g.canvasTop,t=p.paper,n=c.jsonData.chart,f=c.graphics,Q=f.trackerGroup,l,q,w,u,v,g=a.metaTreeInf,e=this.graphics.elemStore,h={},B,C,G=["fontFamily","fontSize","fontWeight","fontStyle"],X={},R,p=p.gradientLegend,aa,x=c._ref,W=x.afAPI.visibilityController,E=c.get("config","animationObj"),H=E.duration||0,F=E.dummyObj,D=E.animObj,y=E.animType,S,E=x.containerManager,x=x.algorithmFactory,ga;d&&(d.length=0);S=ua({},{},n,{fontFamily:"Verdana,sans",
fontSize:"10px"});d=0;for(n=G.length;d<n;d++)ga=G[d],ga in S&&(X[ga]=S[ga]);for(q in e){G=e[q];d=0;for(n=G.length;d<n;d++)(S=G[d])&&S.remove&&S.remove();G.length=0}E.remove();l=f.datasetGroup=f.datasetGroup||t.group("dataset");q=f.datalabelsGroup=(f.datalabelsGroup||t.group("datalabels").insertAfter(l)).css(X);w=f.lineHot=f.lineHot||t.group("line-hot",Q);u=f.labelHighlight=f.labelHighlight||t.group("labelhighlight",q);v=f.floatLabel=f.floatLabel||t.group("labelfloat",q).insertAfter(u);a.colorRange=
p.colorRange;g.effectiveWidth=A-r;g.effectiveHeight=m-k;g.startX=r;g.startY=k;B=g.effectiveWidth/2;C=g.effectiveHeight/2;B=g.effectiveWidth/2;C=g.effectiveHeight/2;h.drawPolyPath=function(a,c){var b,d;b=(h.graphicPool(!1,"polyPathItem")||(d=t.path(l))).attr({path:a._path}).animateWith(F,D,{path:a.path},H,y);b.css(c);d&&e.polypath.push(d);return b};h.drawRect=function(a,c,b,d){var u,f,q={},w={},v;for(u in a)f=a[u],0>f&&(a[u]=0,w.visibility="hidden");oa(q,a);q.x=B;q.y=C;q.height=0;q.width=0;R=h.graphicPool(!1,
"plotItem")||(v=t.rect(l));R.attr(b&&(b.x||b.y)&&b||q);R.attr(d);R.animateWith(F,D,a,H,y,W.controlPostAnimVisibility);R.css(c).toFront();R.css(w);v&&e.rect.push(v);return R};h.drawText=function(c,b,d,l,q){var f={},w,k,m=h.graphicPool(!1,"labelItem")||(w=t.text(v)),g=h.graphicPool(!1,"highlightItem")||(k=t.text(u)),n=d.textAttrs;d=d.highlightAttrs;oa(f,n);delete f.fill;f["stroke-linejoin"]="round";m.attr({x:l.x||B,y:l.y||C,fill:"#000000"}).css(n);m.attr(q);c=0>b.x||0>b.y?ea:c;m.animateWith(F,D,{text:c,
x:b.x,y:b.y},H,y);g.attr({text:c,x:l.x||B,y:l.y||C,stroke:a.labelGlow?"#ffffff":wa}).css(f).css(d);g.attr(q);g.animateWith(F,D,{x:b.x,y:b.y},H,y);e.label.push(w);e.highlight.push(k);return{label:m,highlightMask:g}};h.drawHot=function(a,c){var b;b=a.plotItem||{};var d=a.rect,h,l,q;for(l in d)q=d[l],0>q&&(d[l]=0);b=b.tracker=t.rect(w).attr(d).attr({cursor:"pointer",fill:"rgba(255, 255, 255, 0)",stroke:"none"});for(h in c)d=c[h],b[h].apply(b,d);e.hot.push(b);return b};h.disposeItems=function(a,c){var b,
e,d,l=c||"plotItem labelItem hotItem highlightItem polyPathItem pathlabelItem pathhighlightItem stackedpolyPathItem stackedpathlabelItem stackedpathhighlightItem".split(" ");for(b=0;b<l.length;b+=1)d=l[b],(e=a[d])&&h.graphicPool(!0,d,e,a.rect),e&&e.hide(),a[d]=void 0};h.disposeChild=function(){var a,b=function(){return a.disposeItems},c=function(a,e){var d,h;b(a);for(d=0;d<(a.getChildren()||[]).length;d++)h=a.getChildren(),d=c(h[d],d);return e};return function(e){var d=e.getParent();a||(a=this,b=
b());d?a.disposeChild(d):c(e,0)}}();h.graphicPool=function(){var a={};return function(b,c,e){var d=a[c];d||(d=a[c]=[]);"hotItem"!==c&&"pathhotItem"!==c||e.remove();if(b)d.push(e);else if(b=d.splice(0,1)[0])return b.show(),b}}();h.disposeComplimentary=function(a){var b,c;b=a.getParent();var e=a.getSiblingCount("left");b&&(c=b.getChildren(),b=c.splice(e,1)[0],this.disposeChild(a),c.splice(e,0,b));this.removeLayers()};h.removeLayers=function(){var a,b,c,d;c=e.hot;d=c.length;for(a=0;a<d;a++)(b=c[a])&&
b.remove();c.length=0};x.init(a.algorithm,!0,a.maxDepth);c=x.plotOnCanvas(this.JSONData,void 0,c._getCleanValue());E.init(this,g,h,void 0,c);E.draw();aa=x.applyShadeFiltering({fill:a.rangeOutBgColor,opacity:.01*a.rangeOutBgAlpha},function(a){this.plotItem&&this.plotItem.css(a)});p&&p.enabled&&(p.resetLegend(),p.clearListeners());p.notifyWhenUpdate(function(a,b){aa.call(this,{start:a,end:b})},this);a.isConfigured=!1;b.trackerDrawID.push(fa.addJob(this.kdTreePartioning,this,[],J.priorityList.tracker))}}]);
ja=function(a,c,d){function b(a,b,c){this.node=a;this.bucket=b?new P:void 0;this.cleansingFn=c}var g,p,r,A;b.prototype.get=function(){var a=this.order,b=this.bucket,c=this.cleansingFn;return function f(d,l){var q,w,u,v;w=["label","value","data","svalue"];if(d)for(v in q=new x(d.label,c(d.value),c(d.svalue)),u=d.data||[],0===u.length&&b&&b.addInBucket(q),q.setDepth(l),d)-1===w.indexOf(v)&&q.setMeta(v,d[v]);a&&(u=a(u));for(w=0;w<u.length;w++)v=u[w],v=f(v,l+1),q.addChild(v);return q}(this.node,0)};b.prototype.getBucket=
function(){return this.bucket};b.prototype.getMaxDepth=function(){return p};g=function(a,b){function c(a){this.iterAPI=a}var d=b&&b.exception,f,g;c.prototype.constructor=c;c.prototype.initWith=function(a){return this.iterAPI(a)};f=(new c(function(a){var b=a,c=[],f=!1;c.push(b);return{next:function(a){var b,h;if(!f){b=c.shift();if(d&&b===d&&(b=c.shift(),!b)){f=!0;return}(h=(a=void 0!==a?b.getDepth()>=a?[]:b.getChildren():b.getChildren())&&a.length||0)&&[].unshift.apply(c,a);0===c.length&&(f=!0);return b}},
reset:function(){f=!1;b=a;c.length=0;c.push(b)}}})).initWith(a);g=(new c(function(a){var b=a,c=[],d=[],f=!1;c.push(b);d.push(b);return{next:function(){var a,b,d;if(!f)return b=c.shift(),(d=(a=b.getChildren())&&a.length||0)&&[].push.apply(c,a),0===c.length&&(f=!0),b},nextBatch:function(){var a,b;if(!f)return a=d.shift(),(b=(a=a.getChildren())&&a.length||0)&&[].push.apply(d,a),0===c.length&&(f=!0),a},reset:function(){f=!1;b=a;c.length=0;c.push(b)}}})).initWith(a);return{df:f,bf:g}};A=function(){function a(){this.con=
{}}var b={},c;a.prototype.constructor=a;a.prototype.get=function(a){return this.con[a]};a.prototype.set=function(a,b){this.con[a]=b};a.prototype["delete"]=function(a){return delete this.con[a]};return{getInstance:function(d){var f;return(f=b[d])?c=f:c=b[d]=new a}}}();c=function(){var a=[],b,c=!1,d={visibility:"visible"};return{controlPreAnimVisibility:function(d,n){var l,q,w;if(d){for(q=d;;){q=q.getParent();if(!q)break;l=q}l=g(l,{exception:d});for(l=l.df;;){q=l.next();if(!q)break;w=q.overAttr||(q.overAttr=
{});w.visibility="hidden";a.push(q)}b=n||d.getParent();c=!1;return a}},displayAll:function(d){var n;if(d){d=g(d.getParent()||d);for(d=d.df;;){n=d.next();if(!n)break;n=n.overAttr||(n.overAttr={});n.visibility="visible"}b=void 0;a.length=0;c=!1}},controlPostAnimVisibility:function(){var f,r;if(!c&&(c=!0,b)){r=g(b);for(r=r.df;;){f=r.next(p);if(!f)break;if(f=f.dirtyNode)f&&f.plotItem.attr(d),(f=f&&f.textItem)&&f.label&&f.label.attr(d),f&&f.label&&f.highlightMask.attr(d)}b=void 0;a.length=0}}}}();a.AbstractTreeMaker=
b;a.iterator=g;a.initConfigurationForlabel=function(a,b,c){var d=a.x,f=a.y,g=b/2,l=c.showParent?0:1,q=c.showChildLabels;return function(a,u,v,e){v=!1;var h={x:void 0,y:void 0,width:void 0,height:void 0},B={},C=0,m={},r={},R,m=a.meta;if(a)return a.isLeaf(p)||(v=!0),B.label=a.getLabel(),h.width=u.width-2*d,h.x=u.x+u.width/2,a=u.height-2*f,!v&&a<b&&(h.height=-1),!e&&v?(h.height=q?h.height?h.height:u.height-2*f:-1,h.y=u.y+u.height/2):l?(h.y=-1,b=f=0,R="hidden"):(h.height=h.height?h.height:b,h.y=u.y+f+
g),C+=2*f,C+=b,B.rectShiftY=C,B.textRect=h,c.labelGlow?(r["stroke-width"]=c.labelGlowRadius,r.opacity=c.labelGlowIntensity,r.stroke=c.labelGlowColor,r.visibility="hidden"===R?"hidden":"visible"):r.visibility="hidden",m={fill:m&&m.fontcolor&&ba(m.fontcolor)||c.labelFontColor||c.baseFontColor,visibility:R},{conf:B,attr:m,highlight:r}}};a.context=A;a.mapColorManager=function(a,b,c){var d=ba(c?a.defaultNavigationBarBGColor:a.defaultParentBGColor);return function(c,g,l){g={};var q=c.cssConf,w=c.meta,w=
w.fillcolor?ba(w.fillcolor):void 0,u=c.getParent(),v;v=c.getColorValue();a.isLegendEnabled=!0;v=a.isLegendEnabled&&v===v?b.getColorByValue(v)&&"#"+b.getColorByValue(v)||ba(b.rangeOutsideColor):void 0;c.isLeaf(p)?g.fill=w||v||d:(c=(c=(u?u:c).cssConf)&&c.fill,g.fill=w||(v?v:c));g.stroke=l?a.navigationBarBorderColor:a.plotBorderColor;g.strokeWidth=l?a.navigationBarBorderThickness:a.plotBorderThickness;g["stroke-dasharray"]="none";!l&&q&&"--"===q["stroke-dasharray"]&&(g["stroke-dasharray"]=q["stroke-dasharray"],
g.strokeWidth=q.strokeWidth);return g}};a.abstractEventRegisterer=function(b,c,g,n){function f(a){var b={},c,d;for(c in x)d=x[c],b[d]=a[c];return b}var p=c.chart,l=p.components,q=l.dataset[0],w=l.toolbarBtns,u=p.chartInstance,v=c.conf,e=l.gradientLegend,h=b.drawTree,B=n.disposeChild,C,G=p.getJobList(),X=arguments,R,A,x={colorValue:"svalue",label:"name",value:"value",rect:"metrics"};R=a.context.getInstance("ClickedState");p._intSR={};p._intSR.backToParent=C=function(b){var c=this,d=c,e=d&&c.getParent(),
l=a.context.getInstance("ClickedState").get("VisibileRoot")||{};p.config.trackerConfig.length=0;G.trackerDrawID.push(fa.addJob(q.kdTreePartioning,q,[],J.priorityList.tracker));b?z("beforedrillup",{node:c,withoutHead:!v.showParent},u,void 0,function(){e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(d),h.apply(e,X));z("drillup",{node:c,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u);c=c&&c.getParent()},function(){z("drillupcancelled",{node:c,withoutHead:!v.showParent},u)}):
(e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(d),h.apply(e,X)),c=c&&c.getParent())};p._intSR.resetTree=A=function(c){var b=this,d=b&&b.getParent(),e,l=a.context.getInstance("ClickedState").get("VisibileRoot")||{};p.config.trackerConfig.length=0;for(G.trackerDrawID.push(fa.addJob(q.kdTreePartioning,q,[],J.priorityList.tracker));d;)e=d,d=d.getParent();c?z("beforedrillup",{node:b,withoutHead:!v.showParent},u,void 0,function(){e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},
e],B(e),h.apply(e,X),z("drillup",{node:b,sender:p.fusionCharts,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u))},function(){z("drillupcancelled",{node:b,withoutHead:!v.showParent},u)}):e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(e),h.apply(e,X))};return{click:function(a,c){var h=a.virginNode,l=q.graphics.singleTracker,g=q.kdTree,k,t,G;z("dataplotclick",f(a.virginNode),u);if(t=h.getParent()){if(h===c)G=t,g&&(g.length=0),p.config.trackerConfig.length=0,k="drillup";else{if(h.next)G=
h,g&&(g.length=0);else if(G=t,c===G){k=void 0;return}p.config.trackerConfig.length=0;k="drilldown"}e&&e.enabled&&e.resetLegend();b.applyShadeFiltering.reset();k&&z("before"+k,{node:G,withoutHead:!v.showParent},u,void 0,function(){R.set("VisibileRoot",{node:a,state:k});B.call(n,G);r=G;d.draw();z(k,{node:G,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u)},function(){z(k+"cancelled",{node:G,withoutHead:!v.showParent},u)});w.back&&w.back.attachEventHandlers({click:C.bind(G)});w.home&&w.home.attachEventHandlers({click:A.bind(G)});
l&&l.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"})}},mouseover:function(a){var c=f(a.virginNode);z("dataplotrollover",c,u,void 0,void 0,function(){z("dataplotrollovercancelled",c,u)})},mouseout:function(a){var c=f(a.virginNode),b=q.graphics.singleTracker;b&&b.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"});z("dataplotrollout",f(a.virginNode),u,void 0,void 0,function(){z("dataplotrolloutcancelled",c,u)})}}};a.setMaxDepth=function(a){return p=a};a.getVisibleRoot=function(){return r};
a.setVisibleRoot=function(a){r=a};a.visibilityController=c;return a};ka=function(a,c){function d(){A.apply(this,arguments)}function b(c,b,f){k=new d(c,n,b);c=k.get();!1!==f&&(t=c);a.setVisibleRoot(c);return c}function g(){var b=r[m],d;c.realTimeUpdate=p.apply(this,arguments);d=Array.prototype.slice.call(arguments,0);d.unshift(b);b.drawTree.apply(a.getVisibleRoot(),d)}function p(){var a,c,b=r[m];c=Array.prototype.slice.call(arguments,0);c.unshift(b);a=c.slice(-1)[0];return function(){var d=Array.prototype.slice.call(arguments,
0),f=d.shift(),e=d.shift();ha(t,function(a){b.drawTree.apply(a||t,c)},a,f)[e].apply(this,d)}}var r,A=a.AbstractTreeMaker,m,k,t,n,f,x;r={sliceanddice:{areaBaseCalculator:function(a,c){return function(b,d,f){var e,h,B={},g,n,k,p=e=0;if(b){f&&(e=f.textMargin||e);p=e;f=b.getParent();e=b.getSibling("left");if(f){h=f.getValue();k=f.rect;g=k.height-2*c-p;n=k.width-2*a;B.effectiveRect={height:g,width:n,x:k.x+a,y:k.y+c+p};B.effectiveArea=g*n;B.ratio=b.getValue()/h;if(e)return d.call(b,B,e,f);B.lastIsParent=
!0;return d.call(b,B,f)}return null}}},applyShadeFiltering:function(a,c,b){a.setRangeOutEffect(c,b);this.applyShadeFiltering.reset=function(){a.resetPointers()};return function(c){a.moveLowerShadePointer(c.start);a.moveHigherShadePointer(c.end)}},alternateModeManager:function(){return function(a,c){var b,d,f,e,h,B=a.effectiveArea*a.ratio;d=a.effectiveRect;var g=c.rect;a.lastIsParent?(e=d.x,h=d.y,b=d.height,d=d.width,f=this.isDirectionVertical=!0):(b=d.height+d.y-(g.height+g.y),d=d.width+d.x-(g.width+
g.x),f=this.isDirectionVertical=!c.isDirectionVertical);f?(d=B/b,e=void 0!==e?e:g.x,h=void 0!==h?h:g.y+g.height):(b=B/d,e=void 0!==e?e:g.x+g.width,h=void 0!==h?h:g.y);return{height:b,width:d,x:e,y:h}}},horizontalVerticalManager:function(a){var c="vertical"===a?!0:!1;return function(a,b,d){var e,h,f,l=a.effectiveArea*a.ratio,g=a.effectiveRect,k=b.rect;a.lastIsParent?(h=g.x,f=g.y,a=g.height,e=g.width,b=this.isDirectionVertical=!b.isDirectionVertical):(a=g.height+g.y-(k.height+k.y),e=g.width+g.x-(k.width+
k.x),b=this.isDirectionVertical=!d.isDirectionVertical);(b=c?b:!b)?(0===a&&(a=g.height,h=void 0!==h?h:k.x+k.width,f=void 0!==f?f:k.y),e=l/a,h=void 0!==h?h:k.x,f=void 0!==f?f:k.y+k.height):(0===e&&(e=g.width,h=void 0!==h?h:k.x,f=void 0!==f?f:k.y+k.height),a=l/e,h=void 0!==h?h:k.x+k.width,f=void 0!==f?f:k.y);return{height:a,width:e,x:h,y:f}}},drawTree:function(c,b,d,g){var k=b.chart,e=k.components,h=k.config||(k.config={}),B=h.trackerConfig||(h.trackerConfig=[]),n=e.numberFormatter,e=e.toolbarBtns,
p=g.drawRect,t=g.drawText,r=g.drawHot,h=d.horizontalPadding,m=d.verticalPadding,A=b.chart.linkedItems.smartLabel,y=a.iterator,E=y(this).df,H,F=c.areaBaseCalculator(h,m),D=b.conf,K=D.highlightParentsOnHover,S,z=a.context,h=a.visibilityController,N=a.mapColorManager(D,b.conf.colorRange),m=a.abstractEventRegisterer.apply(a,arguments),T=m.click,ia=m.mouseover,L=m.mouseout,m=D.slicingMode,M=c["alternate"===m?"alternateModeManager":"horizontalVerticalManager"](m),m=k._intSR,I,y=z.getInstance("ClickedState").get("VisibileRoot")||
{};(I=y.node)&&y.state&&("drillup"===y.state.toLowerCase()?I instanceof Array?h.controlPreAnimVisibility(I[0].virginNode,I[1]):h.controlPreAnimVisibility(I.virginNode):h.displayAll(y.node.virginNode));S=a.initConfigurationForlabel({x:5,y:5},D.parentLabelLineHeight,D);for(h=H=E.next(x=a.setMaxDepth(this.getDepth()+f));h.getParent();)h=h.getParent();D.showNavigationBar?(e.home.hide(),e.back.hide()):h!=H?(e.home.show(),e.back.show()):(e.home.hide(),e.back.hide());A.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);
A.setStyle(D._setStyle={fontSize:(D.labelFontSize||D.baseFontSize)+"px",fontFamily:D.labelFont||D.baseFont,lineHeight:1.2*(D.labelFontSize||D.baseFontSize)+"px"});k=m.backToParent;h=m.resetTree;e.back&&e.back.attachEventHandlers({click:k.bind(H)});e.home&&e.home.attachEventHandlers({click:h.bind(H)});(function U(a,c){var b,d,e,h,f,l,q,k;l={};var w,v,m={},y={};q={};var aa="",W,I;a&&(W=n.yAxis(a.getValue()),I=n.sYAxis(a.getColorValue()),a.setPath(),b=a.rect||{},d=a.textRect||{},e=a.rect={},q=a.textRect=
{},e.width=c.width,e.height=c.height,e.x=c.x,e.y=c.y,q=N(a),(v=a.plotItem)&&g.graphicPool(!0,"plotItem",v,b),v=a.plotItem=p(e,q,b,a.overAttr),a.cssConf=q,k=S(a,e),h=k.conf,l.textMargin=h.rectShiftY,q=a.textRect=h.textRect,w=A.getSmartText(h.label,q.width,q.height).text,a.plotItem=v,(h=a.labelItem)?(f=a.highlightItem,g.graphicPool(!0,"labelItem",h,b),g.graphicPool(!0,"highlightItem",f,b)):d=d||{},d=t(w,q,{textAttrs:k.attr,highlightAttrs:k.highlight},d,a.overAttr),a.labelItem=d.label,a.highlightItem=
d.highlightMask,m.virginNode=a,m.plotItem=v,m.textItem=d,m.virginNode.dirtyNode=m,a.getColorValue()&&(aa=D.tooltipSeparationCharacter+I),m.toolText=D.showTooltip?J.parseTooltext(D.plotToolText,[1,2,3,119,122],{label:a.getLabel(),formattedValue:W,formattedsValue:I},{value:a.getValue(),svalue:a.getColorValue()})||a.getLabel()+D.tooltipSeparationCharacter+W+aa:ea,m.rect=e,y.hover=[function(a){var b,c,d;d=z.getInstance("hover");c=this.virginNode;b=K&&!c.next?(b=c.getParent())?b:c:this.virginNode;d.set("element",
b);d=da(qa(b.cssConf.fill,80),60);a.attr({fill:d});ia(this)}.bind(m),function(){var a,b;a=z.getInstance("hover").get("element");b=da(a.cssConf.fill||"#fff",0);a.plotItem.tracker.attr({fill:b});L(this)}.bind(m)],y.tooltip=[m.toolText],y.click=[function(){T(this,H)}.bind(m)],(e=a.hotItem)&&g.graphicPool(!0,"hotItem",e,b),B.push({node:a,key:"hotItem",plotDetails:m,evtFns:y,callback:r}),b=E.next(x),l=F(b,M,l),U(b,l))})(H,d)}},squarified:{orderNodes:function(){return this.sort(function(a,b){return parseFloat(a.value,
10)<parseFloat(b.value,10)?1:-1})},areaBaseCalculator:function(a,b){return function(c,d,f){var e={},h,g=h=0,k,m;if(c&&0!==c.length)return f&&(h=f.textMargin||h),g=h,k=c[0],(c=k.getParent())?(m=c.rect,f=m.height-2*b-g,h=m.width-2*a,e.effectiveRect={height:f,width:h,x:m.x+a,y:m.y+b+g},e.effectiveArea=f*h,d.call(k,e,c)):null}},layoutManager:function(){function a(b,c){this.totalValue=c;this._rHeight=b.height;this._rWidth=b.width;this._rx=b.x;this._ry=b.y;this._rTotalArea=b.height*b.width;this.nodes=[];
this._prevAR=void 0;this._rHeight<this._rWidth&&(this._hSegmented=!0)}a.prototype.constructor=a;a.prototype.addNode=function(a){var b=this._rTotalArea,c,d,e,h,f,g,l,k=this._hSegmented,m=this._rx,n=this._ry,p,t,r,A,x=0;this.nodes.push(a);e=0;for(d=this.nodes.length;e<d;e++)x+=parseFloat(this.nodes[e].getValue(),10);c=x/this.totalValue*b;k?(b=this._rHeight,d=c/b,p=m+d,t=n,r=this._rHeight,A=this._rWidth-d):(d=this._rWidth,b=c/d,p=m,t=n+b,r=this._rHeight-b,A=this._rWidth);e=0;for(h=this.nodes.length;e<
h;e++)a=this.nodes[e],f=a.getValue(),g=f/x*c,a.hRect=a.rect||{},a._hRect=a._rect||{},f=a.rect={},k?(f.width=l=d,f.height=l=g/l,f.x=m,f.y=n,n+=l):(f.height=l=b,f.width=l=g/l,f.x=m,f.y=n,m+=l),g=Y(f.height,f.width),f=na(f.height,f.width),a.aspectRatio=g/f;if(1<this.nodes.length){if(this.prevAR<a.aspectRatio){this.nodes.pop().rect={};e=0;for(d=this.nodes.length;e<d;e++)this.nodes[e].rect=1===d&&this.nodes[e].firstPassed?this.nodes[e]._hRect:this.nodes[e].hRect,k=this.nodes[e]._rect={},m=this.nodes[e].rect,
k.width=m.width,k.height=m.height,k.x=m.x,k.y=m.y;return!1}}else a&&(k=a._rect={},m=a.rect,k.width=m.width,k.height=m.height,k.x=m.x,k.y=m.y,a.firstPassed=!0);this.prevAR=a.aspectRatio;this.height=b;this.width=d;this.getNextLogicalDivision=function(){return{height:r,width:A,x:p,y:t}};return a};return{RowLayout:a}}(),applyShadeFiltering:function(a,b,c){a.setRangeOutEffect(b,c);this.applyShadeFiltering.reset=function(){a.resetPointers()};return function(b){a.moveLowerShadePointer(b.start);a.moveHigherShadePointer(b.end)}},
drawTree:function(b,c,d,g){var k=c.chart,e=k.config||(k.config={}),h=e.trackerConfig||(e.trackerConfig=[]),e=k.components,m=e.numberFormatter,e=e.toolbarBtns,n=b.areaBaseCalculator(d.horizontalPadding,d.verticalPadding),p=b.layoutManager.RowLayout,t=c.chart.linkedItems.smartLabel,r=g.drawRect,A=g.drawText,y=g.drawHot,z=a.iterator,E=z(this).bf,H,F=c.conf,D=F.highlightParentsOnHover,K,S=a.context,P=a.mapColorManager(F,c.conf.colorRange),z=a.abstractEventRegisterer.apply(a,arguments),N=z.click,T=z.mouseover,
ia=z.mouseout,z=k._intSR,L=a.visibilityController,M,I;M=S.getInstance("ClickedState").get("VisibileRoot")||{};(I=M.node)&&M.state&&("drillup"===M.state.toLowerCase()?I instanceof Array?L.controlPreAnimVisibility(I[0].virginNode,I[1]):L.controlPreAnimVisibility(I.virginNode):L.displayAll(M.node.virginNode));K=a.initConfigurationForlabel({x:5,y:5},F.parentLabelLineHeight,F);for(E=H=E.next(x=a.setMaxDepth(this.getDepth()+f));E.getParent();)E=E.getParent();F.showNavigationBar?(e.home.hide(),e.back.hide()):
E!=H?(e.home.show(),e.back.show()):(e.home.hide(),e.back.hide());t.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);t.setStyle(F._setStyle={fontSize:(F.labelFontSize||F.baseFontSize)+"px",fontFamily:F.labelFont||F.baseFont,lineHeight:1.2*(F.labelFontSize||F.baseFontSize)+"px"});k=z.backToParent;z=z.resetTree;e.back&&e.back.attachEventHandlers({click:k.bind(H)});e.home&&e.home.attachEventHandlers({click:z.bind(H)});(function U(a,b){var c,d={},e,f,k,l,q,w,v=0,z,E,I,L;w={};var M;z={};E={};l={};
var V="",W,O;if(a){W=m.yAxis(a.getValue());O=m.sYAxis(a.getColorValue());a.setPath();if(c=a.__initRect)d.x=c.x,d.y=c.y,d.width=c.width,d.height=c.height;k=a.textRect||{};c=a.rect=a.__initRect={};l=a.textRect={};c.width=b.width;c.height=b.height;c.x=b.x;c.y=b.y;l=P(a);(I=a.plotItem)&&g.graphicPool(!0,"plotItem",I,d);I=a.plotItem=r(c,l,d,a.overAttr);a.cssConf=l;M=K(a,c);e=M.conf;w.textMargin=e.rectShiftY;l=a.textRect=e.textRect;L=t.getSmartText(e.label,l.width,l.height).text;(f=a.labelItem)?(e=a.highlightItem,
g.graphicPool(!0,"labelItem",f,d),g.graphicPool(!0,"highlightItem",e,d)):k=k||{};k=A(L,l,{textAttrs:M.attr,highlightAttrs:M.highlight},k,a.overAttr);a.labelItem=k.label;a.highlightItem=k.highlightMask;a.plotItem=I;z.virginNode=a;z.plotItem=I;z.textItem=k;z.virginNode.dirtyNode=z;a.getColorValue()&&(V=F.tooltipSeparationCharacter+O);z.toolText=F.showTooltip?J.parseTooltext(F.plotToolText,[1,2,3,119,122],{label:a.getLabel(),formattedValue:W,formattedsValue:O},{value:a.getValue(),svalue:a.getColorValue()})||
a.getLabel()+F.tooltipSeparationCharacter+W+V:ea;z.rect=c;E.hover=[function(a){var b,c,d;d=S.getInstance("hover");c=this.virginNode;b=D&&!c.next?(b=c.getParent())?b:c:this.virginNode;d.set("element",b);d=b.cssConf;d=da(d.fill&&qa(d.fill,80),60);a.attr({fill:d});T(this)}.bind(z),function(a){var b;b=S.getInstance("hover").get("element").cssConf;b=da(b.fill||"#fff",0);a.attr({fill:b});ia(this)}.bind(z)];E.tooltip=[z.toolText];E.click=[function(){N(this,H)}.bind(z)];(c=a.hotItem)&&g.graphicPool(!0,"hotItem",
c,d);h.push({node:a,key:"hotItem",plotDetails:z,evtFns:E,callback:y});if(q=void 0!==x?a.getDepth()>=x?void 0:a.getChildren():a.getChildren())for(z=n(q,function(a,b){var c,d,e=0,h,f,g=[];c=new p({width:a.effectiveRect.width,height:a.effectiveRect.height,x:a.effectiveRect.x,y:a.effectiveRect.y},b.getValue());for(d=q.length;e++!==d;)h=q[e-1],f=c.addNode(h),!1===f?(c=c.getNextLogicalDivision(),c=new p(c,b.getValue()-v),e--):(v+=parseFloat(h.getValue(),10),g.push(h));return g},w),d=0,w=z.length;d<w;d++)E=
z[d],U(E,E.rect)}})(H,d)}}};d.prototype=Object.create(A.prototype);d.prototype.constructor=A;d.prototype.order=function(a){var b=r[m],c=b.orderNodes;return c?c.apply(a,[b]):a};c.init=function(b,c,d){m=b;n=c;f=a.setMaxDepth(d);return r[m]};c.plotOnCanvas=function(a,c,d){t=b(a,d);return g};c.applyShadeFiltering=function(a,b){var c,d;d=r[m].applyShadeFiltering(k.getBucket(),a,b);return function(a){c=Array.prototype.slice.call(arguments,0);c.unshift(a);d.apply(k.getBucket(),c)}};c.setTreeBase=function(a){return a&&
(t=a)};c.realTimeUpdate=p;c.makeTree=b;return c};ha=function(a,c,d,b){function g(b){var c,d=0;c=a;if(!b.length)return a;for(;c;){c=p.call(c,b[d]);if(d===b.length-1&&c)return r=c.getValue(),c;d+=1}}function p(a){var b,c,d,g=this.getChildren()||[],f=g.length;for(b=0;b<f;b+=1)if(d=g[b],d.label.toLowerCase().trim()===a.toLowerCase().trim()){c=d;break}return c}var r;return{deleteData:function(a,b){var k=g(a),p=(void 0).iterator(k).df,n=k&&k.getParent(),f=k&&k.getSiblingCount("left"),x=n&&n.getChildren(),
l=(void 0).getVisibleRoot();if(k&&n){x.splice(f,1);for(k===l&&(l=k.getParent()||l);k;)d.disposeItems(k),k=p.next();for(;n;)n.setValue(-r,!0),n=n.getParent();b&&c(l)}},addData:function(a,d,k,p){for(var n,f,r,l=0,q=!0,w=(void 0).getVisibleRoot();a.length;)if(n=a.pop(),n=(void 0).makeTree(n,b,!1),l=n.getValue(),f=g(d||[]))for(f.getChildren()||(r=f.getValue(),q=!1),f.addChildren(n,p);f;)f.setValue(l,q),r&&(l-=r,r=void 0,q=!0),f=f.getParent();k&&c(w)}}};la=function(a,c,d){function b(){}function g(b){var c=
t.plotBorderThickness;m.apply(a.getVisibleRoot(),[x,{width:b.effectiveWidth,height:b.effectiveHeight,x:b.startX,y:b.startY,horizontalPadding:t.horizontalPadding,verticalPadding:t.verticalPadding},n]);t.plotBorderThickness=c}function p(a,b,c){var d=a.width,f=a.height,g=t.seperatorAngle/2;a=["M",a.x,a.y];var k=y(g?f/2*(1-sa(g)):c,15);c=function(a){return{both:["h",d,"v",a,"h",-d,"v",-a],right:["h",d,"v",a,"h",-d,"l",k,-a/2,"l",-k,-a/2],no:["h",d,"l",k,a/2,"l",-k,a/2,"h",-d,"l",k,-a/2,"l",-k,-a/2],left:["h",
d,"l",k,a/2,"l",-k,a/2,"h",-d,"v",-a]}};return{path:a.concat(c(f)[b]),_path:a.concat(c(0)[b]),offset:k}}function r(){var a=Array.prototype.splice.call(arguments,0);a.push(!0);l("navigationBar").apply(this,a)}var x,m,k,t,n,f,z=function(b,c){var f,g,l=a.mapColorManager(t,t.colorRange,!0),m=function(){var a;return{get:function(c,b,d){var e={y:c.startY,height:c.effectiveHeight};b=f[b];var h=b.getParent();e.x=a||(a=c.startX);a=d?a+(e.width=c.effectiveWidth*(b.getValue()/h.getValue())):a+(e.width=c.effectiveWidth/
g);return e},resetAllocation:function(){a=void 0}}}(),r=a.initConfigurationForlabel({x:5,y:5},t.parentLabelLineHeight,t),v=n.drawPolyPath,w=n.drawText,z=n.drawHot,y={navigationHistory:{path:"polyPathItem",label:"pathlabelItem",highlightItem:"pathhighlightItem",hotItem:"pathhotItem"}},H=x.chart,F=H.config.trackerConfig,D=H.components.gradientLegend,H=H.linkedItems.smartLabel,J=function(c){return function(){var b=a.context.getInstance("ClickedState").get("VisibileRoot")||{};F.length=0;b.state="drillup";
b.node=[{virginNode:a.getVisibleRoot()},c];D&&D.enabled&&D.resetLegend();d.draw([c,c,c])}},K=function(){return function(){}},Q=function(){return function(){}},N,T,O,L,M,I,P=t._setStyle,U;N=q.get().navigationBar;L=2*u("navigationBar");P=na(N*k.effectiveHeight-(L+6),P.fontSize.replace(/\D+/g,""));N=P+"px";y.stacked={path:"stacked"+y.navigationHistory.path,label:"stacked"+y.navigationHistory.label,highlightItem:"stacked"+y.navigationHistory.highlightItem,hotItem:"stacked"+y.navigationHistory.hotItem};
m.resetAllocation();(function(c){var b=a.getVisibleRoot();f=c?b.getChildren():b.getPath()||[].concat(b);f.pop();g=f.length})(c);H.setStyle({fontSize:N,lineHeight:N});for(N=0;N<g;N+=1)L=f[N],M=m.get(b,N,c),T=(O=p(M,c?"both":1===g?"both":0===N?"left":N<g-1?"no":"right")).offset,L[y[c?"stacked":"navigationHistory"].path]=v(O,l(L,!0,!0),N),O=r(L,M,!1,!0),I=O.conf,U=I.textRect,U.width-=2*T,U.y=M.y+M.height/2,T=H.getSmartText(I.label,U.width,Y(P,U.height)).text,T=w(T,U,{textAttrs:O.attr,highlightAttrs:O.highlight},
{y:M.height/10,"font-size":t._setStyle.fontSize,"font-family":t._setStyle.fontFamily},(c?"stacked":"")+"path"),L[y[c?"stacked":"navigationHistory"].label]=T.label,L[y[c?"stacked":"navigationHistory"].highlightItem]=T.highlightMask,F.push({node:L,key:y[c?"stacked":"navigationHistory"].hotItem,plotDetails:{rect:M},evtFns:{click:[J(L,c)],hover:[K(L),Q()],tooltip:[t.showTooltip?L.getLabel():ea]},callback:z})},l=function(a){return{treeMap:g,navigationBar:z,stackedNavigation:r}[a]},q=function(){var a={treeMap:1,
navigationBar:0,stackedNavigation:0};return{set:function(c){var b=y(t.navigationBarHeightRatio,t.navigationBarHeight/k.effectiveHeight,.15),d=t.labelFontSize?Y(t.labelFontSize,t.baseFontSize):t.baseFontSize,f=2*u("navigationBar"),b=Y((6+d+f)/k.effectiveHeight,b);.1>b?b=.1:.15<b&&(b=.15);t.navigationBarHeightRatio=b;a=c?{treeMap:1-b,navigationBar:b,stackedNavigation:0}:{treeMap:1,navigationBar:0,stackedNavigation:0}},get:function(){return a}}}(),w=0,u=function(a){var b=t.plotBorderThickness,c=t.navigationBarBorderThickness;
return t.verticalPadding+("navigationBar"===a?c:b)},v=function(a){var b=k.effectiveWidth,c=k.effectiveHeight,d=u(a);a=q.get()[a];1<=w&&(w=0);w+=a;return{effectiveHeight:ma(a*c*100)/100-d,effectiveWidth:b,startX:k.startX,startY:k.startY+d+ma((w-a)*c*100)/100}};b.prototype.constructor=b;b.prototype.init=function(a,b){(this.conf||(this.conf={})).name=a.name;this.setDrawingArea(a.drawingAreaMeasurement);this.draw=this.draw(b)};b.prototype.setDrawingArea=function(a){this.conf.drawingAreaMeasurement=a};
b.prototype.draw=function(a){return function(){var b=this.conf;0<b.drawingAreaMeasurement.effectiveHeight&&a(b.drawingAreaMeasurement)}};b.prototype.eventCallback=function(){};f=function(){var a=[];return{get:function(){return a},set:function(c){var d;c?(d=new b,d.init({name:c.type,drawingAreaMeasurement:c.drawingArea},c.drawFn),a.push(d)):a.length=0;return a}}}();d.init=function(){var a,b=["navigationBar","treeMap","stackedNavigation"];a=Array.prototype.slice.call(arguments,0);x=a[0];k=a[1];t=x.conf;
n=a[2];m=a[4];for(f.get().length>=b.length&&f.set();b.length;)a=b.shift(),f.set({type:a,drawFn:l(a),drawingArea:v(a)})};d.draw=function(b){var c,g,k;c=a.getVisibleRoot();n.disposeChild(c);b&&(c=b[1]);c.getParent()?t.showNavigationBar&&d.heightProportion.set(!0):d.heightProportion.set(!1);g=f.get();for(c=0;c<g.length;c+=1)k=g[c],k.setDrawingArea(v(k.conf.name)),b&&a.setVisibleRoot(b[c]),k.draw()};d.heightProportion=q;d.remove=function(){var b=a.getVisibleRoot();b&&n.disposeChild(b)};return d}}])});
